//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryRental
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdProperty { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.TimeSpan TimeEnd { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Property Property { get; set; }
    }
}
