//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homes
    {
        public int Id { get; set; }
        public int AmountPeople { get; set; }
        public string Square { get; set; }
        public int IdType { get; set; }
    
        public virtual TypeOfHome TypeOfHome { get; set; }
        public virtual Property Property { get; set; }
    }
}
