//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionDB : DbContext
    {
        public ConnectionDB()
            : base("name=ConnectionDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Homes> Homes { get; set; }
        public virtual DbSet<TypeOfHome> TypeOfHome { get; set; }
        public virtual DbSet<TypeOfTechnic> TypeOfTechnic { get; set; }
        public virtual DbSet<Technic> Technic { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<HistoryRental> HistoryRental { get; set; }
    }
}
